
family = "noto-glyf_colr_1"
output_file = "noto-glyf_colr_1.ttf"
color_format = "glyf_colr_1"
clipbox_quantization = 32

[axis.wght]
name = "Weight"
default = 400

[master.regular]
style_name = "Regular"
srcs = ["emoji_u1f4ad.svg", "emoji_u1f4af.svg"]

[master.regular.position]
wght = 400
